version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/cache/nginx:/var/cache/nginx
    ports:
      - 8080:8080
    networks:
      - my_network

networks:
  my_network:
